# Generated by Django 5.2.5 on 2025-09-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_livro_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='desconto',
            field=models.FloatField(),
        ),
    ]
