# Generated by Django 5.2.5 on 2025-10-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_livro_disponivel_alter_livro_desconto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magem', models.ImageField(upload_to='upload/%Y%m%d/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
