# Generated by Django 5.2.5 on 2025-10-17 11:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='magem',
        ),
        migrations.AddField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(default=1, upload_to='capas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.path_capa),
        ),
        migrations.AlterField(
            model_name='livro',
            name='dimensoes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livro',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
